version: 0.2

env:
  variables:
     docker_username: docker_username
     docker_password: docker_password
     docker_url: docker_url
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install -r python-application/requirements.txt
      # - command
  build:
    commands:
      - cd python-application
      - echo "Building Docker Image"
      - echo docker login --username "$docker_username" --password "$docker_password"
      - docker build -t "$docker_url/$docker_username/project4-image:latest" .
      - docker push "$docker_url/$docker_username/project4-image:latest"
      # - command
  post_build:
    commands:
      - echo "Build is Successful"
