version: 0.2

env:
  variables:
     docker_username: "miauu57"
     docker_password: "Candy007!"
     docker_url: "docker.io"
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install -r python-application/requirements.txt
      # - command
  build:
    commands:
      - cd python-application
      - echo "Building Docker Image"
      - echo "$docker_password" | docker login -u "$docker_username" --password-stdin "$docker_url"
      - docker build -t "docker.io/miauu57/project4-image:latest" .
      - docker push "docker.io/miauu57/project4-image:latest"
      # - command
  post_build:
    commands:
      - echo "Build is Successful"
